name: Node.js CI

on: [push}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CHeckout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Istall dependencies
        run: npm install

      - name: Run tests
        run: npm test
